//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoupeWS", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class CoupeWS : UnitTestProject1.ServiceReference1.EntityObjectWS {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObjectWS", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnitTestProject1.ServiceReference1.CoupeWS))]
    public partial class EntityObjectWS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceQuiddich")]
    public interface IServiceQuiddich {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuiddich/GetAllCoupes", ReplyAction="http://tempuri.org/IServiceQuiddich/GetAllCoupesResponse")]
        UnitTestProject1.ServiceReference1.CoupeWS[] GetAllCoupes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceQuiddich/GetAllCoupes", ReplyAction="http://tempuri.org/IServiceQuiddich/GetAllCoupesResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.CoupeWS[]> GetAllCoupesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceQuiddichChannel : UnitTestProject1.ServiceReference1.IServiceQuiddich, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceQuiddichClient : System.ServiceModel.ClientBase<UnitTestProject1.ServiceReference1.IServiceQuiddich>, UnitTestProject1.ServiceReference1.IServiceQuiddich {
        
        public ServiceQuiddichClient() {
        }
        
        public ServiceQuiddichClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceQuiddichClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuiddichClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceQuiddichClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestProject1.ServiceReference1.CoupeWS[] GetAllCoupes() {
            return base.Channel.GetAllCoupes();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.ServiceReference1.CoupeWS[]> GetAllCoupesAsync() {
            return base.Channel.GetAllCoupesAsync();
        }
    }
}
